language: node_js
node_js:
  - "0.10"
  - "0.11"
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.11
script:
  - openssl aes-256-cbc -K $encrypted_3cd111abc019_key -iv $encrypted_3cd111abc019_iv -in .travis.id_rsa.enc -out .travis.id_rsa -d
  - cp .travis.id_rsa ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email test@welder.io
  - git config --global user.name welder-io-ci
  - npm test
